### PR TITLE
Add COVID packet and update LBD Short Version

### PR DESCRIPTION
**Pull request by s-emerson**
This pull request adds the COVID module to NACCulator for submission to the NACC site.
It also accounts for updates to the LBD Short Version module, adding the B2L and B6L options to the Z1X and removing fields that are no longer present in the module.

This change was made to expand NACCulator's capabilities after the changes introduced due to the pandemic and to fix a bug that was caused by NACC's DED not matching up with the information on its forms.

## Verification

_List the steps needed to make sure this thing works. Be precise._

1. Collect test COVID module data from our TESTING 1Florida ADRC REDCap project (the COVID module is present at the bottom of the data dictionary: forms "F1: COVID Technology Accessibility Survey", "F2: COVID-19 Impact Survey - Participant", and "F3: COVID-19 Impact Survey - Co-participant".
2. From the command-line, run: 
`redcap2nacc -cv <test_input.csv >test_output.txt`
3. The output should look like regular NACCulator output with the CV packet ID, ready to submit to NACC.
4. If you pass _some bad value_, the output should look like NACCulator errors printed to the command line.

5. The command for testing LBD Short Version data is:
`redcap2nacc -lbdsv -ivp <test_input.csv >test_output.txt`

- Verify the thing does this: produces COVID and LBD Short Version fixed-width text files that are ready for NACC submission.
- Verify the thing does not do that: causes KeyErrors or prints data outside of NACC's expected format.

## Affirmations

All of these should have a check by them. Any exception requires an explanation.

* [x] I matched the style of the existing code.
* [x] I added and updated any relevant documentation (inline, `README`, `CHANGELOG`, and such).
* [x] I used Python's type hinting.
* [x] I ran the automated tests and ensured they **ALL** passed.
* [x] I ran the linter and ensured my changes have not introduced **ANY** warnings or errors.
* [x] I have made an effort to minimize code changes and have not included any cruft (preference files, *.pyc files, old comments, print-debugging, unused variables).
* [x] I have made an effort maintain a clear commit history (haven't merged other branches or rebased improperly).
* [x] I have written the code myself or have given credit where credit is due.

### CODE REVIEW

**Comment by s-emerson** [comment]
> Notes from Code Review:
> 
> 1. Assuming I need to install this version/pull request by checking out this feature branch and doing a "$ pip3 install ."
> 2. Assume the data for this step, "Collect test COVID module data from our TESTING 1Florida ADRC REDCap project.", is just from the form "F2: COVID Participant"
> 3. Ran "$redcap2nacc -cv <test_input.csv >test_output.txt", got error: "Traceback (most recent call last):
>    File "/usr/local/lib/python3.9/site-packages/nacc/redcap2nacc.py", line 427, in convert
>    packet = cv_builder.build_cv_form(record)
>    File "/usr/local/lib/python3.9/site-packages/nacc/cv/builder.py", line 22, in build_cv_form
>    add_f1(record, packet)
>    File "/usr/local/lib/python3.9/site-packages/nacc/cv/builder.py", line 32, in add_f1
>    F1.C19TVIS  = record['C19TVIS'.lower()]
>    KeyError: 'c19tvis'"
> 
> Will need some more detailed testing steps for this pull request if the above steps were incorrect.

Error comes from step 2. Since NACC's COVID module includes all 3 forms as mandatory, NACCulator is built to assume all 3 COVID forms (F1, F2, and F3) are present in the project/input file.
So the KeyError you see in step 3 ('c19tvis') is actually the first field in the COVID module, present at the top of form F1. I will specify in the pull request instructions that the COVID module is all 3 forms.

**Comment by senrabc** [comment]
Tested branch with what appears to be errors.

Steps to reproduce:

1. Enter COVID BASELINE (sub id= XXX424) Form data entered into test project, data is present in the exported data. 

2. RUN:

$redcap2nacc <TESTING1FloridaAlzhe_DATA_2021-08-06_1026.csv >TESTINGdata.txt

3. RUN:

$ cat TESTINGdata.txt | grep -ir F1 

I can do the same grep and see the C1 form data in the output file TESTINGdata.txt, but no F1 data?

When I run. 

$redcap2nacc -lbdsv -ivp <TESTING1FloridaAlzhe_DATA_2021-08-06_1026.csv >test_lbd_output.txt


I get a zero byte output file:   0 Aug  6 10:33 test_lbd_output.txt

**Comment by s-emerson** [comment]
> Tested branch with what appears to be errors.
> 
> Steps to reproduce:
> 
> 1. Enter COVID BASELINE (sub id= XXX424) Form data entered into test project, data is present in the exported data.
> 2. RUN:
> 
> $redcap2nacc <TESTING1FloridaAlzhe_DATA_2021-08-06_1026.csv >TESTINGdata.txt
> 
> 1. RUN:
> 
> $ cat TESTINGdata.txt | grep -ir F1
> 
> I can do the same grep and see the C1 form data in the output file TESTINGdata.txt, but no F1 data?
> 
> When I run.
> 
> $redcap2nacc -lbdsv -ivp <TESTING1FloridaAlzhe_DATA_2021-08-06_1026.csv >test_lbd_output.txt
> 
> I get a zero byte output file: 0 Aug 6 10:33 test_lbd_output.txt

Error comes from step 2. Please use the -cv flag when running NACCulator for COVID data rather than no flag (if no flags are specified, NACCulator defaults to Initial Visit Packet (IVP) module).

The other error comes from the test data. Looking on the Record Status Dashboard of the TESTING project, I see that we have no sample LBD packets filled out. I will resolve that issue, my apologies.

**Comment by senrabc** [comment]
Ok, went back and filled out the correct F1 form (my bad) for a participant that shows up in the nacculator output (xxx007) and still got no F1 on the output. There IS A* , B*, C*, D* and Z1 output. Please advise.

**Comment by melimore86** [comment]
I was able to test the -cv and the -lbdsv -ivp and it does work, needed to install the modules a different way, and it did work, received correct errors

**Review by melimore86 — COMMENTED** [review]
tested and approved

**Pull request merged**
